#!/usr/bin/env python3
# Generate src/assets/Airports.h - a compact US airport + radio-frequency table for
# the Aircraft tab's "nearest airport + likely frequency" feature.
#
# SOURCE: OurAirports (https://ourairports.com), a public-domain dataset that
# aggregates the FAA's NASR data for US fields. Two CSVs:
#   airports.csv             - ident, type, lat/lon, country
#   airport-frequencies.csv  - per-airport TWR/GND/ATIS/AWOS/CTAF/UNICOM frequencies
# To refresh: re-run this script (it re-downloads the CSVs). For the authoritative FAA
# 28-day cycle instead, swap in the NASR APT_BASE.csv / FRQ.csv and keep the same
# emit format below.
#
# Record (16 bytes): id[4] (space-padded ident) + int16 lat*100,lon*100 (0.01 deg ~
# 0.6 nm) + uint16 twr,gnd,atis,ctaf as freqMHz*40 (25 kHz steps, 0 = none).
import csv, os, sys, urllib.request

TMP = os.environ.get('TEMP') or os.environ.get('TMP') or '/tmp'
BASE = 'https://davidmegginson.github.io/ourairports-data/'
FILES = {'airports.csv': 'airports.csv', 'freqs.csv': 'airport-frequencies.csv'}

def fetch(local, remote):
    path = os.path.join(TMP, local)
    if not os.path.exists(path) or os.path.getsize(path) < 1000:
        print('downloading', remote, file=sys.stderr)
        urllib.request.urlretrieve(BASE + remote, path)
    return path

ap_csv = fetch('airports.csv', FILES['airports.csv'])
fq_csv = fetch('freqs.csv', FILES['freqs.csv'])

# airport_ident -> { freq-type: MHz } (airband 108-137 MHz only; first wins)
freqs = {}
for r in csv.DictReader(open(fq_csv, encoding='utf-8')):
    try: f = float(r['frequency_mhz'])
    except ValueError: continue
    if not (108.0 <= f <= 137.0): continue
    freqs.setdefault(r['airport_ident'], {}).setdefault(r['type'], f)

def pick(d, *types):
    for t in types:
        if t in d: return d[t]
    return None

def f40(mhz):
    return int(round(mhz * 40)) if mhz else 0

rows = []
WANT = {'large_airport', 'medium_airport', 'small_airport'}
for a in csv.DictReader(open(ap_csv, encoding='utf-8')):
    if a['iso_country'] != 'US' or a['type'] not in WANT: continue
    ident = a['ident']
    if len(ident) > 4: continue                       # skip the ~9 odd long idents
    d = freqs.get(ident)
    if not d: continue
    twr  = f40(pick(d, 'TWR'))
    gnd  = f40(pick(d, 'GND'))
    atis = f40(pick(d, 'ATIS', 'AWOS', 'ASOS'))
    ctaf = f40(pick(d, 'CTAF', 'UNIC'))
    if not (twr or gnd or atis or ctaf): continue
    try:
        lat = int(round(float(a['latitude_deg']) * 100))
        lon = int(round(float(a['longitude_deg']) * 100))
    except ValueError: continue
    if not (-9000 <= lat <= 9000 and -18000 <= lon <= 18000): continue
    rows.append((ident.ljust(4), lat, lon, twr, gnd, atis, ctaf))

rows.sort(key=lambda r: r[0])
print(f'{len(rows)} airports  flash={len(rows)*16} bytes', file=sys.stderr)

out = ['#pragma once', '#include <stdint.h>', '',
 '// assets/Airports - US airport + radio-frequency table for the Aircraft tab nearest-',
 '// airport feature. Generated by tools/gen_airports.py from OurAirports (public-domain,',
 '// FAA-sourced for US fields) - do not hand-edit. id is the ident space-padded to 4;',
 '// lat/lon are degrees*100; freqs are MHz*40 (25 kHz steps), 0 = none.',
 'struct AirportRec { char id[4]; int16_t lat100, lon100; uint16_t twr, gnd, atis, ctaf; };',
 '',
 'static const AirportRec kAirports[] = {']
for id4, lat, lon, twr, gnd, atis, ctaf in rows:
    c = ','.join("'%s'" % (ch if ch != ' ' else ' ') for ch in id4)
    out.append('  {{%s},%d,%d,%d,%d,%d,%d},' % (c, lat, lon, twr, gnd, atis, ctaf))
out += ['};', 'static const int kAirportCount = sizeof(kAirports) / sizeof(kAirports[0]);', '']
open(sys.argv[1], 'w').write('\n'.join(out))
print('wrote', sys.argv[1], file=sys.stderr)
