#!/usr/bin/env python3
# Generate src/assets/Coastline.h from Natural Earth GeoJSON.
# Output: lon/lat polylines in TENTHS of a degree (int16), {9999,9999} pen-up.
# Sources (real data, not fabricated):
#   - ne_110m_admin_0_countries  -> coastlines + international borders (global)
#   - ne_50m_admin_1_states_provinces (US/CA/AU/BR subset) -> state/province lines
import json, sys, math, os
TMP = os.environ.get('TEMP') or os.environ.get('TMP') or '/tmp'

def rings(geom):
    t = geom['type']; c = geom['coordinates']
    if t == 'LineString':      return [c]
    if t == 'MultiLineString': return c
    if t == 'Polygon':         return c            # outer + holes, each a ring
    if t == 'MultiPolygon':    return [r for poly in c for r in poly]
    return []

def simplify(pts, eps):
    # Closed rings (first==last) break plain RDP (degenerate base segment), so
    # split the ring at the vertex farthest from the first point first.
    if len(pts) > 3 and abs(pts[0][0] - pts[-1][0]) < 1e-9 and abs(pts[0][1] - pts[-1][1]) < 1e-9:
        ax, ay = pts[0]
        k = max(range(1, len(pts) - 1), key=lambda i: (pts[i][0]-ax)**2 + (pts[i][1]-ay)**2)
        return rdp(pts[:k + 1], eps)[:-1] + rdp(pts[k:], eps)
    return rdp(pts, eps)

def rdp(pts, eps):
    # Douglas-Peucker on an open polyline of (lon,lat) in degrees.
    if len(pts) < 3: return pts
    dmax, idx = 0.0, 0
    ax, ay = pts[0]; bx, by = pts[-1]
    dx, dy = bx - ax, by - ay
    nrm = math.hypot(dx, dy) or 1e-9
    for i in range(1, len(pts) - 1):
        px, py = pts[i]
        d = abs((px - ax) * dy - (py - ay) * dx) / nrm
        if d > dmax: dmax, idx = d, i
    if dmax > eps:
        return rdp(pts[:idx + 1], eps)[:-1] + rdp(pts[idx:], eps)
    return [pts[0], pts[-1]]

def emit(feats, eps, want=None, prop='adm0_a3'):
    out = []  # list of polylines, each a list of (lon10,lat10)
    for f in feats:
        if want is not None and f['properties'].get(prop) not in want: continue
        g = f.get('geometry')
        if not g: continue
        for r in rings(g):
            r = [(p[0], p[1]) for p in r if len(p) >= 2]
            if len(r) < 2: continue
            r = simplify(r, eps)
            poly, last = [], None
            for lon, lat in r:
                q = (int(round(lon * 10)), int(round(lat * 10)))
                if q != last and -1800 <= q[0] <= 1800 and -900 <= q[1] <= 900:
                    poly.append(q); last = q
            if len(poly) >= 2: out.append(poly)
    return out

countries = json.load(open(os.path.join(TMP, 'ne_country.json')))['features']
states    = json.load(open(os.path.join(TMP, 'ne_states.json')))['features']

world  = emit(countries, eps=0.45)                                   # global: coast + intl borders
provs  = emit(states,    eps=0.18, want={'USA', 'CAN', 'AUS', 'BRA'}) # regional: state/province lines

def block(name, polys):
    npts = sum(len(p) + 1 for p in polys)
    print(f'{name}: polylines={len(polys)} segs={npts} flash={npts*4} bytes', file=sys.stderr)
    out = [f'static const CoastPt {name}[] = {{']
    for p in polys:
        out.append('  ' + ''.join('{%d,%d},' % (x, y) for x, y in p) + '{9999,9999},')
    out += ['};', f'static const int {name}Count = sizeof({name}) / sizeof({name}[0]);', '']
    return out

L = ['#pragma once', '#include <stdint.h>', '',
 '// assets/Coastline - world coastlines + international borders (Natural Earth 110m',
 '// admin_0) in kCoastline, plus US/CA/AU/BR state & province lines (Natural Earth 50m',
 '// admin_1) in kStateLines. Generated by tools/gen_worldmap.py from real Natural Earth',
 '// data - do not hand-edit. Coords are lon,lat in TENTHS of a degree (int16).',
 '// {9999,9999} is a pen-up separator between polylines.',
 'struct CoastPt { int16_t lon; int16_t lat; };', '']
L += block('kCoastline', world)
L += block('kStateLines', provs)
open(sys.argv[1], 'w').write('\n'.join(L))
print('wrote', sys.argv[1], file=sys.stderr)
